// Generated by CoffeeScript 1.3.3
(function() {
  var createTable, http, options, table, _i, _len, _ref;

  http = require('http');

  options = {
    host: '127.0.0.1',
    port: 5984
  };

  createTable = function(table) {
    var req;
    options.path = "/" + table;
    options.method = 'PUT';
    req = http.request(options, function(res) {
      console.log("headers: " + (JSON.stringify(res.headers)));
      res.setEncoding('utf8');
      return res.on('data', function(chunk) {
        return console.log("chunk: " + chunk);
      });
    });
    req.on('error', function(e) {
      return console.log("error: " + e.message);
    });
    return req.end();
  };

  _ref = ["test_stories", "test_tasks"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    table = _ref[_i];
    createTable(table);
  }

}).call(this);
