// Generated by CoffeeScript 1.3.3
(function() {
  var fs, path;

  fs = require('fs');

  path = './script/views';

  fs.readFile("" + path + "/stories/sprint_backlog/map.js", 'utf8', function(error, data) {
    return console.log(data);
  });

  fs.readdir("" + path + "/", function(err, tables) {
    var crateView, table, _i, _len, _results;
    crateView = function(table) {
      var view;
      view = {
        _id: "_design/" + table,
        language: "javascript",
        views: {}
      };
      return fs.readdir("" + path + "/" + table + "/", function(err, ids) {
        var createMapReduce, id, _i, _len, _results;
        createMapReduce = function(id) {
          return view.views[id] = {};
        };
        _results = [];
        for (_i = 0, _len = ids.length; _i < _len; _i++) {
          id = ids[_i];
          _results.push(createMapReduce(id));
        }
        return _results;
      });
    };
    _results = [];
    for (_i = 0, _len = tables.length; _i < _len; _i++) {
      table = tables[_i];
      _results.push(crateView(table));
    }
    return _results;
  });

}).call(this);
